---
- name: Run app command - {{app_name}} {{app_action}}
  ansible.builtin.shell: |
    source ~/.dotfiles/source.sh
    app {{ app_name }} {{ app_action }}
  args:
    executable: /bin/zsh
    chdir: "{{ ansible_env.HOME }}"
  register: app_result
  changed_when: false

- name: Show app command output
  ansible.builtin.debug:
    var: app_result.stdout
